added dependabot configuration
streamr-dev/eslint-config-streamr pull request #23
Opened 2021-12-31 12:43 UTC by DaisyDomergue

2021-12-31 12:44 UTC, DaisyDomergue commented
I only added gitaction configurartion I didn't include the docker specification in the dependabot because I don't think this repo utilizes docker

2022-01-03 15:09 UTC, kare approved these changes

2022-01-03 15:10 UTC, kare commented
@DaisyDomergue Note the title! Also try to remember to use conventional commits with the actual commit messages.

2022-01-03 15:11 UTC, kare commented on .github/dependabot.yaml
> +      - kare
Change to `harbu`

2022-01-03 15:13 UTC, kare commented on .github/dependabot.yaml
> +      - DaisyDomergue
Change to `timoxley`

2022-01-03 15:18 UTC, DaisyDomergue commented
changed the assignee and the reviewer

2022-01-03 16:20 UTC, kare commented
@DaisyDomergue Sorry my bad, I thought that I was looking at the Node/Javascript Dependabot config. So GitHub Actions config as usual. Reviewers/assignees I mentioned are for Node/Javascript config. So at the moment it's missing the Node section.

2022-01-03 16:24 UTC, kare requested changes
Also note that you need a Dependabot Node/Javascript section for each type/directory:
- ts
- react
- node.js

2022-01-07 15:26 UTC, DaisyDomergue commented
> Also note that you need a Dependabot Node/Javascript section for each type/directory:
> 
>     * ts
> 
>     * react
> 
>     * node.js

I don't we require such configurations since all of them use npm as the main package manager I think that is enough.

2022-01-12 15:07 UTC, kare commented on .github/dependabot.yaml
> +    directory: "/"
Path is missing

2022-01-18 10:58 UTC, kare commented on .github/dependabot.yaml
> +      prefix: Build
Label is `build`

2022-01-18 11:01 UTC, kare requested changes
Needs some attention on details.

2022-01-18 11:08 UTC, DaisyDomergue commented on .github/dependabot.yaml
> +      - timoxley
I have already fixed it in the second commit [https://github.com/streamr-dev/eslint-config-streamr/pull/23/commits/60149f89632e7c6b3520beecae7c2f9ae48d624e](second commit) can you check that one please

2022-01-18 11:13 UTC, kare approved these changes
LGTM

2022-01-18 11:14 UTC, merged